name: Build utils module

on:
  push:
    branches: [ main ]
    paths:
      - utils
    paths-ignore:
  pull_request:
    branches: [ main ]
    paths:
      - utils


jobs:
  build:
    if: ${{ ! startsWith(github.actor, 'dependabot') }}
    environment: Development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.0.5

    - name: Build utils module
      run: ./gradlew utils:assembleRelease
