name: Release the components

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.0.5
      
    - name: Publish components to Github
      uses: gradle/gradle-build-action@v2
      with:
        arguments: components:publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
